GET {{url}}/api/customers
Authorization: {{auth}}

###
GET {{url}}/api/customers?q={"phone":"9611111111"}
Authorization: {{auth}}

###
GET {{url}}/api/customers/5
Authorization: {{auth}}

###
POST {{url}}/api/customers
Content-Type: application/json
Authorization: {{auth}}

{
  "name": "Arun",
  "phone": "9611111111"
}

###
PATCH {{url}}/api/customers/5
Content-Type: application/json
Authorization: {{auth}}

{
  "name": "arun kumar",
  "email": "arun@gmail.com",
  "address": "Mantri Courtyard",
  "city": "Bangalore",
  "postCode": "560061"
}

###
POST {{url}}/auth/create
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="user"

gowthaman
--WebAppBoundary--
Content-Disposition: form-data; name="auth"

password
--WebAppBoundary--

###
###
POST {{url}}/auth/validate
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="user"

gowthaman
--WebAppBoundary--
Content-Disposition: form-data; name="auth"

password
--WebAppBoundary--

###